#!/usr/bin/env bash

set -e

### recreate docker-compose env

make dc_rm dc_get dc_up
sleep 5

### create or upgrade Kong Admin API loopback requiring auth
unset KONG_ADMIN_URL # http://localhost:8001 is the default
kong-incubator --yaml examples/kadmin.yaml 1>/dev/null
sleep 5
export KONG_ADMIN_KEY=$(kong-incubator --key-auth root --output key)
echo -e "\nRestricted http://localhost:8000/kadmin to key-auth: $KONG_ADMIN_KEY"

### example to create a proxy requiring auth to mockbin.com

export KONG_ADMIN_URL="http://localhost:8000/kadmin"
kong-incubator --yaml examples/mockbin.yaml 1>/dev/null
sleep 5
export MOCKBIN_MOCKER_KEY=$(kong-incubator --key-auth mocker --output key)
echo -e "\nRestricted http://localhost:8000 to key-auth: $MOCKBIN_MOCKER_KEY"
