#!/usr/bin/env bash

set -e

### recreate env and install package from source
make --silent dc_rm dc install

unset KONG_ADMIN_KEY
unset KONG_ADMIN_URL

### create or upgrade Kong Admin API loopback requiring auth
kong-incubator --yaml examples/kadmin.yaml --output None
admin_key=$(kong-incubator --key-auth root --output key)
echo "Send header 'apikey:$admin_key' to authenticate http://localhost:8000/kadmin"

### example to create a new service via the authenticated Admin API
KONG_ADMIN_URL=http://localhost:8000/kadmin kong-incubator \
  --admin-key=$admin_key \
  --yaml examples/mockbin.yaml \
  --output None

mockbin_key=$(KONG_ADMIN_KEY=$admin_key kong-incubator \
  --admin-url=http://localhost:8000/kadmin \
  --key-auth mocker \
  --output key)

echo "Send header 'apikey:$mockbin_key' to authenticate http://localhost:8000"