version: 2
jobs:
  tests:
    docker:
      - image: circleci/python:3.6
      - image: kong:0.13
      - image: postgres:10
    steps:
      - checkout
      - run:
          name: install
          command: ./dev/install.sh
      - run:
          name: flake8
          command: flake8
      - run:
          name: test
          command: pytest --cov
      - run:
          name: upload coverage
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build-deploy:
    jobs:
      - tests
